### ISSUE TITLE
GraphQL Introspection?

### ISSUE THREAD

**Issue by Hacksore** [producthunt/producthunt-api#313]
Do y’all support it cause when I tried I get various errors.

trying with `https://ph-graph-api-explorer.herokuapp.com/graphql` (assuming this is wrong)

```
> graphql-codegen --config codegen.ts

[STARTED] Parse Configuration
[SUCCESS] Parse Configuration
[STARTED] Generate outputs
[STARTED] Generate to /Users/hacksore/code/opensource/<concealed by 1Password>/src/__generated/graphql.ts
[STARTED] Load GraphQL schemas
[FAILED] 
[FAILED]         Failed to load schema from https://ph-graph-api-explorer.herokuapp.com/graphql:
[FAILED] 
[FAILED]         Query has depth of 15, which exceeds max depth of 13
[FAILED]         GraphQLError: Query has depth of 15, which exceeds max depth of 13
[FAILED]     at createGraphQLError (/Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+utils@10.5.4_graphql@16.9.0/node_modules/@graphql-tools/utils/cjs/
errors.js:31:12)
[FAILED]     at /Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+wrap@10.0.5_graphql@16.9.0/node_modules/@graphql-tools/wrap/cjs/introspect.js:12:102
[FAILED]     at Array.map (<anonymous>)
[FAILED]     at getSchemaFromIntrospection (/Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+wrap@10.0.5_graphql@16.9.0/node_modules/@graphql-tools/wra
p/cjs/introspect.js:12:58)
[FAILED]     at /Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+wrap@10.0.5_graphql@16.9.0/node_modules/@graphql-tools/wrap/cjs/introspect.js:35:32
[FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[FAILED]     at async UrlLoader.load (/Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+url-loader@8.0.2_@types+node@20.14.10_graphql@16.9.0/node_module
s/@graphql-tools/url-loader/cjs/index.js:221:29)
[FAILED]     at async /Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+load@8.0.2_graphql@16.9.0/node_modules/@graphql-tools/load/cjs/load-typedefs/loa
d-file.js:14:39
[FAILED]     at async Promise.all (index 5)
[FAILED]     at async loadFile (/Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+load@8.0.2_graphql@16.9.0/node_modules/@graphql-tools/load/cjs/load-ty
pedefs/load-file.js:12:9)
[FAILED]     at async /Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+load@8.0.2_graphql@16.9.0/node_modules/@graphql-tools/load/cjs/load-typedefs/col
lect-sources.js:191:25
```

trying with `https://api.producthunt.com/v2/api/graphql`

```
> graphql-codegen --config codegen.ts

[STARTED] Parse Configuration
[SUCCESS] Parse Configuration
[STARTED] Generate outputs
[STARTED] Generate to /Users/hacksore/code/opensource/<concealed by 1Password>/src/__generated/graphql.ts
[STARTED] Load GraphQL schemas
[FAILED] 
[FAILED]         Failed to load schema from https://api.producthunt.com/v2/api/graphql:
[FAILED] 
[FAILED]         undefined
[FAILED]         GraphQLError
[FAILED]     at createGraphQLError (/Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+utils@10.5.4_graphql@16.9.0/node_modules/@graphql-tools/utils/cjs/
errors.js:31:12)
[FAILED]     at /Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+wrap@10.0.5_graphql@16.9.0/node_modules/@graphql-tools/wrap/cjs/introspect.js:12:102
[FAILED]     at Array.map (<anonymous>)
[FAILED]     at getSchemaFromIntrospection (/Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+wrap@10.0.5_graphql@16.9.0/node_modules/@graphql-tools/wra
p/cjs/introspect.js:12:58)
[FAILED]     at /Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+wrap@10.0.5_graphql@16.9.0/node_modules/@graphql-tools/wrap/cjs/introspect.js:35:32
[FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[FAILED]     at async UrlLoader.load (/Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+url-loader@8.0.2_@types+node@20.14.10_graphql@16.9.0/node_module
s/@graphql-tools/url-loader/cjs/index.js:221:29)
[FAILED]     at async /Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+load@8.0.2_graphql@16.9.0/node_modules/@graphql-tools/load/cjs/load-typedefs/loa
d-file.js:14:39
[FAILED]     at async Promise.all (index 5)
[FAILED]     at async loadFile (/Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+load@8.0.2_graphql@16.9.0/node_modules/@graphql-tools/load/cjs/load-ty
pedefs/load-file.js:12:9)
[FAILED]     at async /Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+load@8.0.2_graphql@16.9.0/node_modules/@graphql-tools/load/cjs/load-typedefs/col
lect-sources.js:191:25
```

trying with `https://www.producthunt.com/frontend/graphql` (certainly this is the most illegal)
```
> graphql-codegen --config codegen.ts

[STARTED] Parse Configuration
[SUCCESS] Parse Configuration
[STARTED] Generate outputs
[STARTED] Generate to /Users/hacksore/code/opensource/<concealed by 1Password>/src/__generated/graphql.ts
[STARTED] Load GraphQL schemas
[FAILED] 
[FAILED]         Failed to load schema from https://www.producthunt.com/frontend/graphql:
[FAILED] 
[FAILED]         Failed to find any GraphQL type definitions in: https://www.producthunt.com/frontend/graphql;
[FAILED]  - Field '__schema' doesn't exist on type 'Query'
[FAILED]   - Fragment FullType was defined, but not used
[FAILED]         AggregateError: Failed to find any GraphQL type definitions in: https://www.producthunt.com/frontend/graphql;
[FAILED]  - Field '__schema' doesn't exist on type 'Query'
[FAILED]   - Fragment FullType was defined, but not used
[FAILED]     at loadFile (/Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+load@8.0.2_graphql@16.9.0/node_modules/@graphql-tools/load/cjs/load-typedefs
/load-file.js:35:19)
[FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[FAILED]     at async /Users/hacksore/code/opensource/<concealed by 1Password>/node_modules/.pnpm/@graphql-tools+load@8.0.2_graphql@16.9.0/node_modules/@graphql-tools/load/cjs/load-typedefs/col
lect-sources.js:191:25
```

**Comment by Hacksore** [comment]
@RStankov would you be able to help demystify this?

**Comment by Hacksore** [comment]
Closing as I believe https://github.com/producthunt/producthunt-api/issues/296 is probably accurate.

**Comment by Hacksore** [comment]
Well maybe that client wasn't working cause in postman im seeing this which means introspection has to be working.

<img width="1387" alt="Image" src="https://github.com/user-attachments/assets/88ebc1c3-7a41-40fe-9832-2d6f35db852b" />
